version: '3'
services:

  mongo:
    image: mongo:${SOFTWARE_VERSION_TAG}
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${SOFTWARE_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - '172.17.0.1:8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${SOFTWARE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://admin:${SOFTWARE_PASSWORD}@mongo:27017/
    depends_on:
      - mongo