version: "3"
services:
  mongo:
    image: mongo:${SOFTWARE_VERSION_TAG}
    container_name: mongo
    restart: always
    dns:
      - 8.8.8.8
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "Cluster0"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${SOFTWARE_PASSWORD}
    volumes:
      - ./data:/data/db
      - ./auth/key:/auth/key
    ports:
      - "17271:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "172.17.0.1:8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${SOFTWARE_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${SOFTWARE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://admin:${SOFTWARE_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
      - mongosetup

  mongosetup:
    image: mongo:${SOFTWARE_VERSION_TAG}
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]
